[package]
name = "jks"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
sqlx = { version = "0.5", features = ["postgres","runtime-actix-rustls"] }
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }